[package]
name = "proxy_canister_types"
version = "0.0.1"
edition = { workspace = true }

[dependencies]
candid = { workspace = true }
serde = { workspace = true }

http_over_ws = { workspace = true }
